import type { LucideIcon } from "lucide-react";
import {
  Layout,
  Navigation,
  PanelBottom,
  Columns3,
  Anchor,
  PanelLeft,
  Frame,
  Type,
  ImageIcon,
  GalleryHorizontal,
  Video,
  Presentation,
  BookOpen,
  Sparkles,
  Clock3,
  ShoppingBag,
  List,
  CreditCard,
  ShoppingCart,
  CheckCircle,
  Banknote,
  PackageCheck,
  Star,
  HelpCircle,
  Share2,
  Building2,
  MessageCircle,
  Bell,
  Phone,
  AppWindow,
  MousePointerClick,
  LayoutList,
  MessageSquareDot,
  Timer,
  Mail,
  Layers2,
  PanelRightClose,
  Zap,
  Code2,
  Map,
  ArrowRightCircle,
  Undo2,
  Menu,
  Minus,
  Megaphone,
  Globe,
} from "lucide-react";
import type { BlockType } from "@/types/builder";

export const BLOCK_ICON_MAP: Partial<Record<BlockType, LucideIcon>> = {
  "block-hero": Layout,
  "block-header": Navigation,
  "block-footer": PanelBottom,
  "block-columns": Columns3,
  "block-anchor": Anchor,
  "block-sidebar": PanelLeft,
  "block-frame": Frame,

  "block-text": Type,
  "block-image": ImageIcon,
  "block-gallery": GalleryHorizontal,
  "block-video": Video,
  "block-carousel": Presentation,
  "block-blog-post": BookOpen,
  "block-features": Sparkles,
  "block-changelog": Clock3,

  "block-product-card": ShoppingBag,
  "block-product-list": List,
  "block-pricing": CreditCard,
  "block-checkout": ShoppingCart,
  "block-order-confirm": CheckCircle,
  "block-payment-list": Banknote,
  "block-stock-counter": PackageCheck,

  "block-testimonial": Star,
  "block-faq": HelpCircle,
  "block-social-links": Share2,
  "block-logos": Building2,
  "block-fake-comment": MessageCircle,
  "block-fake-notification": Bell,
  "block-contact": Phone,
  "block-applications": AppWindow,

  "block-button": MousePointerClick,
  "block-button-group": LayoutList,
  "block-float-button": MessageSquareDot,
  "block-countdown": Timer,
  "block-form": Mail,
  "block-popup": Layers2,
  "block-chat-bot": MessageCircle,
  "block-tab": PanelRightClose,
  "block-floating-content": PanelBottom,

  "block-animation": Zap,
  "block-custom-script": Code2,
  "block-custom-html": Globe,
  "block-google-maps": Map,
  "block-auto-redirect": ArrowRightCircle,
  "block-back-redirect": Undo2,
  "block-menu-group": Menu,
  "block-divider": Minus,
};

export const BLOCK_LABEL_MAP: Partial<Record<BlockType, string>> = {
  "block-hero": "Hero",
  "block-header": "Header / Nav",
  "block-footer": "Footer",
  "block-columns": "Columns",
  "block-anchor": "Anchor",
  "block-sidebar": "Sidebar",
  "block-frame": "Iframe",

  "block-text": "Text",
  "block-image": "Image",
  "block-gallery": "Gallery",
  "block-video": "Video",
  "block-carousel": "Carousel",
  "block-blog-post": "Blog Posts",
  "block-features": "Features",
  "block-changelog": "Changelog",

  "block-product-card": "Product Card",
  "block-product-list": "Product List",
  "block-pricing": "Pricing",
  "block-checkout": "Checkout",
  "block-order-confirm": "Order Confirm",
  "block-payment-list": "Payment List",
  "block-stock-counter": "Stock Counter",

  "block-testimonial": "Testimonials",
  "block-faq": "FAQ",
  "block-social-links": "Social Links",
  "block-logos": "Logos",
  "block-fake-comment": "Fake Comments",
  "block-fake-notification": "Notification",
  "block-contact": "Contact",
  "block-applications": "Applications",

  "block-button": "Button",
  "block-button-group": "Button Group",
  "block-float-button": "Float Button",
  "block-countdown": "Countdown",
  "block-form": "Form",
  "block-popup": "Popup",
  "block-chat-bot": "Chat Bot",
  "block-tab": "Tabs",
  "block-floating-content": "Float Content",

  "block-animation": "Animation",
  "block-custom-script": "Custom Script",
  "block-custom-html": "Custom HTML",
  "block-google-maps": "Google Maps",
  "block-auto-redirect": "Auto Redirect",
  "block-back-redirect": "Back Trap",
  "block-menu-group": "Menu Group",
  "block-divider": "Divider",
};
