import type { CronReport, AlertPayload } from '@/types/telegram';

export function formatCronReport(report: CronReport): string {
  const statusEmoji = {
    success: '✅',
    failed: '❌',
    partial: '⚠️',
  };

  const lines: string[] = [
    `${statusEmoji[report.status]} <b>Cron Job: ${report.jobName}</b>`,
    '',
    `📅 <b>Time:</b> ${new Date(report.timestamp).toLocaleString('en-US', { timeZone: 'Asia/Jakarta' })} WIB`,
    `⏱️  <b>Duration:</b> ${(report.duration / 1000).toFixed(2)}s`,
    `📊 <b>Status:</b> ${report.status.toUpperCase()}`,
    '',
  ];

  // Add result details
  if (Object.keys(report.result).length > 0) {
    lines.push('<b>📋 Results:</b>');
    for (const [key, value] of Object.entries(report.result)) {
      lines.push(`  • ${key}: <code>${value}</code>`);
    }
    lines.push('');
  }

  // Add errors if any
  if (report.errors.length > 0) {
    lines.push(`<b>⚠️ Errors (${report.errors.length}):</b>`);
    report.errors.slice(0, 5).forEach((error, i) => {
      lines.push(`  ${i + 1}. ${error.substring(0, 200)}`);
    });
    if (report.errors.length > 5) {
      lines.push(`  ... and ${report.errors.length - 5} more`);
    }
    lines.push('');
  }

  lines.push(`<i>🤖 Generated by Snapland CronBot</i>`);

  return lines.join('\n');
}

export function formatAlert(alert: AlertPayload): string {
  const levelEmoji = {
    info: 'ℹ️',
    warning: '⚠️',
    error: '🔴',
    critical: '🚨',
  };

  const lines: string[] = [
    `${levelEmoji[alert.level]} <b>${alert.title}</b>`,
    '',
    `📝 <b>Message:</b> ${alert.message}`,
    `📍 <b>Source:</b> <code>${alert.source}</code>`,
    `⏰ <b>Time:</b> ${new Date().toLocaleString('en-US', { timeZone: 'Asia/Jakarta' })} WIB`,
  ];

  if (alert.metadata && Object.keys(alert.metadata).length > 0) {
    lines.push('');
    lines.push('<b>📦 Metadata:</b>');
    for (const [key, value] of Object.entries(alert.metadata)) {
      const val = typeof value === 'object' ? JSON.stringify(value) : String(value);
      lines.push(`  • ${key}: <code>${val.substring(0, 100)}</code>`);
    }
  }

  if (alert.error) {
    lines.push('');
    lines.push('<b>💥 Error Details:</b>');
    lines.push(`<pre>${alert.error.message?.substring(0, 500) || 'Unknown error'}</pre>`);
  }

  lines.push('');
  lines.push(`<i>🤖 Generated by Snapland AlertBot</i>`);

  return lines.join('\n');
}

export function formatNewRegistration(data: {
  email: string;
  name: string;
  plan?: string;
  timestamp: string;
}): string {
  return [
    '🎉 <b>New User Registration!</b>',
    '',
    `👤 <b>Name:</b> ${data.name}`,
    `📧 <b>Email:</b> ${data.email}`,
    data.plan ? `💎 <b>Plan:</b> ${data.plan}` : '',
    `⏰ <b>Time:</b> ${data.timestamp}`,
    '',
    `<i>🤖 Snapland Notification</i>`,
  ].filter(Boolean).join('\n');
}

export function formatNewOrder(data: {
  orderId: string;
  customer: string;
  amount: number;
  currency?: string;
  products: number;
}): string {
  return [
    '🛒 <b>New Order Received!</b>',
    '',
    `📦 <b>Order ID:</b> <code>${data.orderId}</code>`,
    `👤 <b>Customer:</b> ${data.customer}`,
    `💰 <b>Amount:</b> ${data.currency || 'IDR'} ${data.amount.toLocaleString()}`,
    `📦 <b>Products:</b> ${data.products} items`,
    '',
    `<i>🤖 Snapland Order Notification</i>`,
  ].join('\n');
}

export function formatErrorReport(data: {
  error: Error;
  route: string;
  userId?: string;
}): string {
  return [
    '💥 <b>Application Error</b>',
    '',
    `📍 <b>Route:</b> <code>${data.route}</code>`,
    data.userId ? `👤 <b>User ID:</b> ${data.userId}` : '',
    '',
    `<b>Error:</b>`,
    `<pre>${data.error.message?.substring(0, 500) || 'Unknown'}</pre>`,
    '',
    data.error.stack ? `<b>Stack:</b>\n<pre>${data.error.stack.substring(0, 1000)}</pre>` : '',
    '',
    `<i>🤖 Snapland Error Report</i>`,
  ].filter(Boolean).join('\n');
}