/**
 * Block Catalog V2 — All 42 block definitions
 * Path: src/lib/builder/block-catalog.ts
 */

import type { BlockDefinition, BlockCategory } from "@/types/builder";

export const BLOCK_CATALOG: BlockDefinition[] = [
  // ════════════════════════════════════════════
  // LAYOUT (7)
  // ════════════════════════════════════════════
  {
    type: "block-hero",
    category: "layout",
    label: "Hero",
    description: "Full-width hero section with headline, subtext, and CTA",
    icon: "Layout",
    defaultProps: {
      headline: "Your Amazing Headline Here",
      subheadline: "A compelling subheadline that converts visitors into customers.",
      ctaText: "Get Started",
      ctaUrl: "",
      ctaSecondaryText: "",
      ctaSecondaryUrl: "",
      backgroundImageUrl: "",
      overlayOpacity: 40,
      minHeight: "500px",
      textAlign: "center",
    },
    defaultLayout: { paddingY: "xl", paddingX: "md", align: "center", maxWidth: "lg" },
  },
  {
    type: "block-header",
    category: "layout",
    label: "Header / Nav",
    description: "Sticky navigation bar with logo, links, and CTA",
    icon: "Menu",
    defaultProps: {
      logoText: "Brand",
      logoUrl: "",
      logoImageUrl: "",
      navLinks: [
        { label: "Features", href: "#features" },
        { label: "Pricing", href: "#pricing" },
        { label: "Contact", href: "#contact" },
      ],
      ctaText: "Get Started",
      ctaUrl: "",
      sticky: true,
      transparent: false,
      showOnScroll: false,
    },
    defaultLayout: { paddingY: "sm", paddingX: "md", maxWidth: "xl" },
  },
  {
    type: "block-footer",
    category: "layout",
    label: "Footer",
    description: "Page footer with links, social, and copyright",
    icon: "Rows",
    defaultProps: {
      logoText: "Brand",
      copyright: `© ${new Date().getFullYear()} Your Brand. All rights reserved.`,
      columns: [
        {
          title: "Product",
          links: [{ label: "Features", href: "#" }, { label: "Pricing", href: "#" }],
        },
      ],
      socialLinks: [],
      showPoweredBy: true,
    },
    defaultLayout: { paddingY: "xl", paddingX: "md", maxWidth: "xl" },
  },
  {
    type: "block-columns",
    category: "layout",
    label: "Columns",
    description: "Multi-column layout (1-6 cols) with responsive grid",
    icon: "Columns",
    defaultProps: {
      columns: 2,
      gap: "md",
      verticalAlign: "top",
      responsive: true,
      items: [
        { content: "Column 1 content", id: "col-1" },
        { content: "Column 2 content", id: "col-2" },
      ],
    },
    defaultLayout: { paddingY: "lg", paddingX: "md", maxWidth: "xl" },
  },
  {
    type: "block-anchor",
    category: "layout",
    label: "Anchor",
    description: "Invisible scroll target for smooth navigation",
    icon: "Anchor",
    defaultProps: { anchorId: "section-id" },
    defaultLayout: { paddingY: "none", paddingX: "none" },
  },
  {
    type: "block-sidebar",
    category: "layout",
    label: "Sidebar",
    description: "Side panel content (sticky or scrollable)",
    icon: "PanelLeft",
    defaultProps: {
      position: "left",
      width: "280px",
      sticky: false,
      content: "Sidebar content here",
    },
    defaultLayout: { paddingY: "lg", paddingX: "md" },
    planRequired: "starter",
  },
  {
    type: "block-frame",
    category: "layout",
    label: "Frame / Embed",
    description: "Embed iFrame (Google Maps, Calendly, Typeform, etc.)",
    icon: "Frame",
    defaultProps: {
      src: "",
      height: "450px",
      title: "Embedded content",
      allowFullscreen: true,
      sandbox: "allow-scripts allow-same-origin",
    },
    defaultLayout: { paddingY: "md", paddingX: "none", maxWidth: "full" },
    planRequired: "starter",
  },

  // ════════════════════════════════════════════
  // CONTENT (8)
  // ════════════════════════════════════════════
  {
    type: "block-text",
    category: "content",
    label: "Text / Rich Text",
    description: "Rich text content (bold, italic, lists, links)",
    icon: "Type",
    defaultProps: {
      html: "<p>Add your content here. You can use <strong>bold</strong>, <em>italic</em>, and more.</p>",
      fontSize: "base",
      lineHeight: "relaxed",
    },
    defaultLayout: { paddingY: "md", paddingX: "md", align: "left", maxWidth: "lg" },
  },
  {
    type: "block-image",
    category: "content",
    label: "Image",
    description: "Single image with optional caption, link, and overlay text",
    icon: "Image",
    defaultProps: {
      src: "",
      alt: "",
      caption: "",
      linkUrl: "",
      linkTarget: "_blank",
      objectFit: "cover",
      aspectRatio: "16/9",
      overlayText: "",
    },
    defaultLayout: { paddingY: "sm", paddingX: "none", maxWidth: "full" },
  },
  {
    type: "block-gallery",
    category: "content",
    label: "Gallery",
    description: "Image gallery (grid or masonry) with lightbox",
    icon: "Images",
    defaultProps: {
      images: [],
      layout: "grid",
      columns: 3,
      gap: "sm",
      lightbox: true,
      aspectRatio: "square",
    },
    defaultLayout: { paddingY: "lg", paddingX: "md", maxWidth: "xl" },
    planRequired: "starter",
  },
  {
    type: "block-video",
    category: "content",
    label: "Video",
    description: "YouTube / TikTok embed or direct video upload",
    icon: "Play",
    defaultProps: {
      platform: "youtube",
      url: "",
      videoId: "",
      caption: "",
      autoplay: false,
      muted: true,
      loop: false,
      showControls: true,
      aspectRatio: "16/9",
    },
    defaultLayout: { paddingY: "md", paddingX: "none", maxWidth: "xl" },
  },
  {
    type: "block-carousel",
    category: "content",
    label: "Carousel / Slider",
    description: "Image/content slider with auto-play, arrows, and dots",
    icon: "SlidersHorizontal",
    defaultProps: {
      items: [],
      autoPlay: true,
      autoPlayInterval: 4000,
      showArrows: true,
      showDots: true,
      infinite: true,
      slidesPerView: 1,
    },
    defaultLayout: { paddingY: "md", paddingX: "none", maxWidth: "full" },
    planRequired: "starter",
  },
  {
    type: "block-blog-post",
    category: "content",
    label: "Blog Posts",
    description: "Blog post grid or list display",
    icon: "FileText",
    defaultProps: {
      layout: "grid",
      columns: 3,
      showDate: true,
      showExcerpt: true,
      showAuthor: false,
      postsPerPage: 6,
      posts: [],
    },
    defaultLayout: { paddingY: "xl", paddingX: "md", maxWidth: "xl" },
    planRequired: "pro",
  },
  {
    type: "block-features",
    category: "content",
    label: "Features / How It Works",
    description: "Feature cards with icon, title, and description — numbered steps or grid",
    icon: "Sparkles",
    defaultProps: {
      style: "grid",
      columns: 3,
      numbered: false,
      items: [
        { icon: "Zap", title: "Fast & Easy", description: "Get started in minutes, no code needed." },
        { icon: "Shield", title: "Secure", description: "Enterprise-grade security built in." },
        { icon: "Star", title: "Powerful", description: "Everything you need to grow." },
      ],
    },
    defaultLayout: { paddingY: "xl", paddingX: "md", maxWidth: "xl" },
  },
  {
    type: "block-changelog",
    category: "content",
    label: "Changelog",
    description: "Version history timeline",
    icon: "History",
    defaultProps: {
      items: [
        { version: "v2.0.0", date: "2024-01-01", changes: ["Major new features", "Performance improvements"] },
      ],
    },
    defaultLayout: { paddingY: "xl", paddingX: "md", maxWidth: "lg" },
    planRequired: "pro",
  },

  // ════════════════════════════════════════════
  // COMMERCE (7)
  // ════════════════════════════════════════════
  {
    type: "block-product-card",
    category: "commerce",
    label: "Product Card",
    description: "Single product showcase with price, image, and buy button",
    icon: "ShoppingBag",
    defaultProps: {
      productId: null,
      showRating: true,
      showBadges: true,
      showDescription: true,
      showSoldCount: false,
      ctaText: "Buy Now",
      layout: "vertical",
    },
    defaultLayout: { paddingY: "lg", paddingX: "md", maxWidth: "md" },
  },
  {
    type: "block-product-list",
    category: "commerce",
    label: "Product List / Grid",
    description: "Multiple products in grid or list layout",
    icon: "LayoutGrid",
    defaultProps: {
      productIds: [],
      layout: "grid",
      columns: 3,
      showRating: true,
      showBadges: true,
      ctaText: "Shop Now",
    },
    defaultLayout: { paddingY: "xl", paddingX: "md", maxWidth: "xl" },
  },
  {
    type: "block-pricing",
    category: "commerce",
    label: "Pricing",
    description: "Pricing plans (card/table) with feature list",
    icon: "CreditCard",
    defaultProps: {
      style: "cards",
      columns: 3,
      pricingItemIds: [],
      showMonthlyToggle: false,
      highlightIndex: 1,
    },
    defaultLayout: { paddingY: "xl", paddingX: "md", maxWidth: "xl" },
    planRequired: "starter",
  },
  {
    type: "block-checkout",
    category: "commerce",
    label: "Checkout Form",
    description: "Complete purchase form with shipping and payment",
    icon: "ShoppingCart",
    defaultProps: {
      fields: {
        name: true,
        phone: true,
        email: false,
        address: true,
        city: true,
        notes: true,
      },
      paymentMethodIds: [],
      logisticId: null,
      showOrderSummary: true,
      submitLabel: "Place Order",
    },
    defaultLayout: { paddingY: "xl", paddingX: "md", maxWidth: "lg" },
    planRequired: "starter",
  },
  {
    type: "block-order-confirm",
    category: "commerce",
    label: "Order Confirmation",
    description: "Post-purchase confirmation page with order details",
    icon: "CheckCircle",
    defaultProps: {
      headline: "Order Received! 🎉",
      subheadline: "Thank you for your purchase. We'll contact you shortly.",
      showOrderNumber: true,
      showOrderSummary: true,
      nextStepText: "What happens next",
      steps: [
        { icon: "Phone", text: "We'll confirm your order via WhatsApp" },
        { icon: "Package", text: "Order is processed and packed" },
        { icon: "Truck", text: "Delivered to your address" },
      ],
    },
    defaultLayout: { paddingY: "xl", paddingX: "md", maxWidth: "lg" },
    planRequired: "starter",
  },
  {
    type: "block-payment-list",
    category: "commerce",
    label: "Payment Methods",
    description: "Display accepted payment method logos/details",
    icon: "Wallet",
    defaultProps: {
      paymentMethodIds: [],
      layout: "grid",
      showAccountNumber: false,
      title: "Payment Methods",
    },
    defaultLayout: { paddingY: "lg", paddingX: "md", maxWidth: "xl" },
    planRequired: "starter",
  },
  {
    type: "block-stock-counter",
    category: "commerce",
    label: "Stock Counter",
    description: "Real-time stock counter with low-stock warning",
    icon: "Package",
    defaultProps: {
      productId: null,
      lowStockThreshold: 10,
      showWhenLow: false,
      label: "Only {count} left in stock!",
      showProgressBar: true,
      initialStock: 100,
    },
    defaultLayout: { paddingY: "sm", paddingX: "md", maxWidth: "md" },
    planRequired: "starter",
  },

  // ════════════════════════════════════════════
  // SOCIAL & TRUST (9)
  // ════════════════════════════════════════════
  {
    type: "block-testimonial",
    category: "social",
    label: "Testimonials",
    description: "Customer reviews (single, grid, or list) with rating",
    icon: "Star",
    defaultProps: {
      style: "grid",
      columns: 3,
      showRating: true,
      showAvatar: true,
      items: [
        { name: "Customer Name", role: "CEO, Company", text: "Amazing product!", rating: 5, avatar: "" },
      ],
    },
    defaultLayout: { paddingY: "xl", paddingX: "md", maxWidth: "xl" },
  },
  {
    type: "block-faq",
    category: "social",
    label: "FAQ",
    description: "Frequently asked questions accordion",
    icon: "HelpCircle",
    defaultProps: {
      showSearch: false,
      openFirst: true,
      items: [
        { question: "What is this product?", answer: "This is an amazing product that helps you grow your business." },
        { question: "How does it work?", answer: "Simply sign up, create your page, and start converting visitors." },
      ],
    },
    defaultLayout: { paddingY: "xl", paddingX: "md", maxWidth: "lg" },
  },
  {
    type: "block-social-links",
    category: "social",
    label: "Social Links",
    description: "Social media and marketplace link buttons",
    icon: "Share2",
    defaultProps: {
      layout: "list",
      showIcon: true,
      showLabel: true,
      buttonStyle: "filled",
      links: [
        { platform: "instagram", label: "Instagram", url: "", icon: "Instagram" },
        { platform: "tiktok", label: "TikTok", url: "", icon: "Music" },
        { platform: "whatsapp", label: "WhatsApp", url: "", icon: "MessageCircle" },
      ],
    },
    defaultLayout: { paddingY: "lg", paddingX: "md", maxWidth: "sm" },
  },
  {
    type: "block-logos",
    category: "social",
    label: "Logo Bar",
    description: "Partner / client logos with optional scrolling marquee",
    icon: "Award",
    defaultProps: {
      title: "Trusted by 1000+ businesses",
      logos: [],
      marquee: false,
      marqueeSpeed: 30,
      grayscale: true,
    },
    defaultLayout: { paddingY: "xl", paddingX: "md", maxWidth: "xl" },
  },
  {
    type: "block-fake-comment",
    category: "social",
    label: "Social Proof Comments",
    description: "Fake social media comments for social proof",
    icon: "MessageCircle",
    defaultProps: {
      platform: "instagram",
      comments: [
        { avatar: "", username: "customer123", text: "This is amazing! Just ordered mine 🔥", likes: 47, time: "2h ago" },
      ],
    },
    defaultLayout: { paddingY: "lg", paddingX: "md", maxWidth: "md" },
    planRequired: "starter",
  },
  {
    type: "block-fake-notification",
    category: "social",
    label: "Fake Notification Toast",
    description: "Social proof toast notifications (e.g. recent purchases)",
    icon: "Bell",
    defaultProps: {
      position: "bottom-left",
      interval: 5000,
      duration: 4000,
      messages: [
        { avatar: "", name: "Ahmad R.", location: "Jakarta", action: "just purchased this product" },
        { avatar: "", name: "Siti M.", location: "Surabaya", action: "is viewing this page" },
      ],
    },
    defaultLayout: { paddingY: "none", paddingX: "none" },
    planRequired: "starter",
  },
  {
    type: "block-contact",
    category: "social",
    label: "Contact",
    description: "Contact form with WhatsApp and email options",
    icon: "Mail",
    defaultProps: {
      title: "Get in Touch",
      subtitle: "We'd love to hear from you",
      fields: { name: true, email: true, phone: true, message: true },
      waRotatorId: null,
      emailNotifId: null,
      submitLabel: "Send Message",
    },
    defaultLayout: { paddingY: "xl", paddingX: "md", maxWidth: "lg" },
  },
  {
    type: "block-applications",
    category: "social",
    label: "Applications",
    description: "Showcase integrated apps and services",
    icon: "AppWindow",
    defaultProps: {
      title: "Integrated with your favorite tools",
      apps: [],
      layout: "grid",
      columns: 4,
    },
    defaultLayout: { paddingY: "xl", paddingX: "md", maxWidth: "xl" },
    planRequired: "pro",
  },

  // ════════════════════════════════════════════
  // INTERACTIVE (9)
  // ════════════════════════════════════════════
  {
    type: "block-button",
    category: "interactive",
    label: "Button",
    description: "CTA button with custom link or WhatsApp Rotator",
    icon: "MousePointerClick",
    defaultProps: {
      text: "Click Here",
      url: "",
      target: "_blank",
      style: "filled",
      size: "lg",
      fullWidth: false,
      icon: "",
      iconPosition: "left",
      waRotatorId: null,
      waTemplateId: null,
    },
    defaultLayout: { paddingY: "md", paddingX: "md", align: "center" },
  },
  {
    type: "block-button-group",
    category: "interactive",
    label: "Button Group",
    description: "Row of multiple buttons",
    icon: "ToggleLeft",
    defaultProps: {
      alignment: "center",
      gap: "md",
      buttons: [
        { text: "Primary Action", url: "", style: "filled", size: "lg" },
        { text: "Secondary Action", url: "", style: "outlined", size: "lg" },
      ],
    },
    defaultLayout: { paddingY: "md", paddingX: "md", align: "center" },
  },
  {
    type: "block-float-button",
    category: "interactive",
    label: "Floating Button",
    description: "Fixed position button (WhatsApp, scroll-to-top, chat)",
    icon: "MessageSquarePlus",
    defaultProps: {
      type: "whatsapp",
      position: "bottom-right",
      waRotatorId: null,
      customUrl: "",
      label: "Chat",
      showLabel: true,
      pulseAnimation: true,
    },
    defaultLayout: { paddingY: "none", paddingX: "none" },
  },
  {
    type: "block-countdown",
    category: "interactive",
    label: "Countdown Timer",
    description: "Countdown to a date with multiple display styles",
    icon: "Timer",
    defaultProps: {
      targetDate: "",
      label: "Offer ends in:",
      style: "minimal",
      showDays: true,
      expiredText: "Offer has ended",
      resetOnExpiry: false,
    },
    defaultLayout: { paddingY: "lg", paddingX: "md", align: "center" },
  },
  {
    type: "block-form",
    category: "interactive",
    label: "Form",
    description: "Contact, subscribe, or newsletter form",
    icon: "ClipboardList",
    defaultProps: {
      title: "Subscribe for Updates",
      fields: [
        { name: "email", label: "Email Address", type: "email", required: true, placeholder: "your@email.com" },
      ],
      submitLabel: "Subscribe",
      successMessage: "Thank you! You've been subscribed.",
      emailNotifId: null,
    },
    defaultLayout: { paddingY: "xl", paddingX: "md", maxWidth: "md", align: "center" },
  },
  {
    type: "block-popup",
    category: "interactive",
    label: "Popup / Dialog",
    description: "Triggered popup for promos, announcements, or lead capture",
    icon: "Maximize2",
    defaultProps: {
      trigger: "time",
      triggerDelay: 5,
      triggerScroll: 50,
      showOnce: true,
      content: "Special Offer: Get 10% off!",
      ctaText: "Claim Now",
      ctaUrl: "",
      showCloseButton: true,
    },
    defaultLayout: { paddingY: "none", paddingX: "none" },
    planRequired: "starter",
  },
  {
    type: "block-chat-bot",
    category: "interactive",
    label: "Chat Bot / Bubble",
    description: "WhatsApp chat bubble with AI or manual agent routing",
    icon: "Bot",
    defaultProps: {
      mode: "manual",
      waRotatorId: null,
      waTemplateId: null,
      greeting: "Hi! How can I help you today?",
      botName: "Support",
      botAvatar: "",
      position: "bottom-right",
      primaryColor: "#25D366",
    },
    defaultLayout: { paddingY: "none", paddingX: "none" },
    planRequired: "starter",
  },
  {
    type: "block-tab",
    category: "interactive",
    label: "Tabs",
    description: "Tabbed content sections",
    icon: "PanelTop",
    defaultProps: {
      defaultTab: 0,
      style: "underline",
      tabs: [
        { label: "Tab 1", content: "Content for tab 1" },
        { label: "Tab 2", content: "Content for tab 2" },
      ],
    },
    defaultLayout: { paddingY: "xl", paddingX: "md", maxWidth: "xl" },
    planRequired: "starter",
  },
  {
    type: "block-floating-content",
    category: "interactive",
    label: "Floating Content",
    description: "Fixed overlay content panel",
    icon: "Layers",
    defaultProps: {
      position: "bottom",
      content: "Special announcement",
      dismissible: true,
    },
    defaultLayout: { paddingY: "none", paddingX: "none" },
    planRequired: "starter",
  },

  // ════════════════════════════════════════════
  // ADVANCED (8)
  // ════════════════════════════════════════════
  {
    type: "block-animation",
    category: "advanced",
    label: "Animation Block",
    description: "Animated arrow, image, or text element",
    icon: "Wand2",
    defaultProps: {
      animationType: "arrow-bounce",
      direction: "down",
      speed: "normal",
      loop: true,
      content: "",
    },
    defaultLayout: { paddingY: "sm", paddingX: "md", align: "center" },
    planRequired: "starter",
  },
  {
    type: "block-custom-script",
    category: "advanced",
    label: "Custom Script",
    description: "Inject a saved script from Applications",
    icon: "Code",
    defaultProps: {
      scriptId: null,
      injectPosition: "body",
    },
    defaultLayout: { paddingY: "none", paddingX: "none" },
    planRequired: "starter",
  },
  {
    type: "block-custom-html",
    category: "advanced",
    label: "Custom HTML / AI Builder",
    description: "Raw HTML block or AI-generated content",
    icon: "Code2",
    defaultProps: {
      html: "<!-- Your custom HTML here -->",
      aiPrompt: "",
    },
    defaultLayout: { paddingY: "none", paddingX: "none" },
  },
  {
    type: "block-google-maps",
    category: "advanced",
    label: "Google Maps",
    description: "Embedded Google Maps with marker",
    icon: "MapPin",
    defaultProps: {
      address: "",
      zoom: 15,
      height: "400px",
      showMarker: true,
      markerLabel: "",
    },
    defaultLayout: { paddingY: "md", paddingX: "none", maxWidth: "full" },
    planRequired: "starter",
  },
  {
    type: "block-auto-redirect",
    category: "advanced",
    label: "Auto Redirect",
    description: "Auto-redirect to URL after countdown delay",
    icon: "ArrowRightCircle",
    defaultProps: {
      targetUrl: "",
      delaySeconds: 5,
      showCountdown: true,
      message: "You will be redirected in {seconds} seconds...",
    },
    defaultLayout: { paddingY: "xl", paddingX: "md", align: "center" },
    planRequired: "starter",
  },
  {
    type: "block-back-redirect",
    category: "advanced",
    label: "Back Redirect Trap",
    description: "Trap browser back button to keep user on page",
    icon: "ArrowLeftCircle",
    defaultProps: {
      enabled: true,
      message: "Are you sure you want to leave?",
      redirectUrl: "",
    },
    defaultLayout: { paddingY: "none", paddingX: "none" },
    planRequired: "pro",
  },
  {
    type: "block-menu-group",
    category: "advanced",
    label: "Menu Group",
    description: "Grouped accordion link menu",
    icon: "List",
    defaultProps: {
      groups: [
        {
          title: "Group 1",
          links: [{ label: "Link 1", href: "#" }, { label: "Link 2", href: "#" }],
        },
      ],
    },
    defaultLayout: { paddingY: "lg", paddingX: "md", maxWidth: "md" },
    planRequired: "starter",
  },
  {
    type: "block-divider",
    category: "advanced",
    label: "Divider",
    description: "Section divider (line, wave, or dots)",
    icon: "Minus",
    defaultProps: {
      style: "line",
      color: "",
      thickness: 1,
      text: "",
    },
    defaultLayout: { paddingY: "sm", paddingX: "md", maxWidth: "xl" },
  },
];

// ── Catalog helpers ───────────────────────────────────────────
export function getBlocksByCategory(category: BlockCategory): BlockDefinition[] {
  return BLOCK_CATALOG.filter((b) => b.category === category);
}

export function getBlockDef(type: string): BlockDefinition | undefined {
  return BLOCK_CATALOG.find((b) => b.type === type);
}

export function searchBlocks(query: string): BlockDefinition[] {
  const q = query.toLowerCase();
  return BLOCK_CATALOG.filter(
    (b) =>
      b.label.toLowerCase().includes(q) ||
      b.description.toLowerCase().includes(q) ||
      b.category.includes(q),
  );
}

export const CATEGORY_META: Record<BlockCategory, { label: string; icon: string; color: string }> = {
  layout: { label: "Layout", icon: "LayoutTemplate", color: "text-violet-500" },
  content: { label: "Content", icon: "FileText", color: "text-blue-500" },
  commerce: { label: "Commerce", icon: "ShoppingBag", color: "text-orange-500" },
  social: { label: "Social", icon: "Users", color: "text-green-500" },
  interactive: { label: "Interactive", icon: "MousePointerClick", color: "text-yellow-500" },
  advanced: { label: "Advanced", icon: "Wand2", color: "text-red-500" },
};

export const CATEGORIES: BlockCategory[] = [
  "layout", "content", "commerce", "social", "interactive", "advanced",
];
