// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "HomePage": {
    "title": "Snapland!",
    "tagline": "AI Landing Page Builder: Create High-Converting Pages in Seconds",
    "description": "Build professional, high-converting landing pages with Landoo.ai. No coding required. Use our AI-powered builder to grow your business and boost conversions instantly."
  },
  "NotFoundPage": {
    "title": "404 Not Found",
    "description": "Looks like you've ventured into the unknown digital realm.",
    "link": "Return to website"
  },
  "LocaleSwitcher": {
    "label": "Change language",
    "locale": "{locale, select, id {Bahasa Indonesia} en {English}}"
  },
  "Manifest": {
    "name": "Snapland"
  }
};
export default messages;